import { verticalNames, type Company } from "@/lib/domain";

const accessedAt = "2026-08-13";
const makeSource = (id: string, title: string) => ({
  id,
  title,
  domain: "demo.prospect-radar.local",
  url: `https://demo.prospect-radar.local/fontes/${id}`,
  accessedAt,
  summary:
    "Fonte fictícia criada exclusivamente para demonstrar a separação entre evidência e análise.",
});
export const demoCompanies: Company[] = [
  {
    id: "demo-aurora",
    name: "Aurora Mercado Digital (Demonstração)",
    tradeName: "Aurora",
    domain: "aurora-demo.example",
    vertical: "Retail",
    subsegment: "Varejo e e-commerce",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    size: "Grande",
    employees: "1.000–5.000",
    description:
      "Empresa fictícia de varejo omnichannel usada apenas para avaliação do produto.",
    solution: "API Security",
    score: 89,
    apiScore: 92,
    waapScore: 84,
    guardicoreScore: 61,
    breakdown: {
      verticalFit: 19,
      sizeComplexity: 14,
      digitalPresence: 19,
      transactionalChannels: 14,
      recentSignals: 13,
      solutionFit: 8,
      evidenceQuality: 2,
    },
    recommendation:
      "Priorizar validação manual por combinar canais digitais e programa de parceiros fictícios.",
    confirmedFacts: [
      "Opera um marketplace fictício descrito na fonte de demonstração.",
      "Mantém aplicativo móvel fictício.",
    ],
    commercialSignals: [
      "Expansão simulada do programa de parceiros.",
      "Vaga fictícia menciona microsserviços.",
    ],
    hypotheses: [
      "Pode haver espaço para conversar sobre governança e proteção de APIs; validar antes da abordagem.",
    ],
    sources: [
      makeSource("aurora-site", "Portal institucional fictício da Aurora"),
      makeSource("aurora-vaga", "Vaga fictícia de engenharia de plataforma"),
    ],
    titles: ["CISO", "Head de AppSec", "Diretor de Plataformas Digitais"],
    navigatorQuery:
      '(CISO OR "Head de Segurança" OR AppSec OR DevSecOps) AND (API OR "Plataformas Digitais")',
    status: "Nova",
    tags: ["demo", "marketplace"],
    discoveredAt: "2026-08-13",
    demo: true,
    possibleDuplicate: false,
  },
  {
    id: "demo-atlas",
    name: "Atlas Serviços Integrados (Demonstração)",
    domain: "atlas-servicos-demo.example",
    vertical: "Business Services",
    subsegment: "Logística",
    city: "Campinas",
    state: "SP",
    country: "Brasil",
    size: "Grande",
    employees: "5.000–10.000",
    description:
      "Operação distribuída fictícia com unidades em diferentes regiões.",
    solution: "Guardicore",
    score: 82,
    apiScore: 58,
    waapScore: 64,
    guardicoreScore: 90,
    breakdown: {
      verticalFit: 18,
      sizeComplexity: 15,
      digitalPresence: 14,
      transactionalChannels: 10,
      recentSignals: 12,
      solutionFit: 10,
      evidenceQuality: 3,
    },
    recommendation:
      "Validar contexto de infraestrutura distribuída e modernização antes de pesquisar personas.",
    confirmedFacts: ["A fonte fictícia lista 24 unidades operacionais."],
    commercialSignals: ["Anúncio fictício de modernização cloud."],
    hypotheses: [
      "A segmentação de ambientes pode ser tema relevante; não há confirmação de necessidade ou vulnerabilidade.",
    ],
    sources: [
      makeSource("atlas-expansao", "Comunicado fictício de expansão regional"),
    ],
    titles: [
      "Head de Infraestrutura",
      "Gerente de Redes",
      "Security Architect",
    ],
    navigatorQuery:
      '("Head de Infraestrutura" OR "Gerente de Redes" OR "Security Architect" OR "Zero Trust")',
    status: "Pendente de validação",
    tags: ["demo", "infraestrutura"],
    discoveredAt: "2026-08-13",
    reviewedAt: "2026-08-13",
    demo: true,
    possibleDuplicate: false,
  },
  {
    id: "demo-horizonte",
    name: "Instituto Horizonte Educação (Demonstração)",
    domain: "horizonte-edu-demo.example",
    vertical: "Education",
    subsegment: "Universidades",
    city: "Curitiba",
    state: "PR",
    country: "Brasil",
    size: "Médio",
    employees: "500–1.000",
    description:
      "Instituição fictícia com portal de alunos e processo seletivo digital.",
    solution: "WAAP",
    score: 76,
    apiScore: 68,
    waapScore: 86,
    guardicoreScore: 55,
    breakdown: {
      verticalFit: 17,
      sizeComplexity: 10,
      digitalPresence: 18,
      transactionalChannels: 12,
      recentSignals: 9,
      solutionFit: 8,
      evidenceQuality: 2,
    },
    recommendation:
      "Investigar manualmente responsáveis por segurança e aplicações digitais.",
    confirmedFacts: ["Possui portal transacional fictício para alunos."],
    commercialSignals: [
      "Campanha fictícia de processo seletivo com sazonalidade.",
    ],
    hypotheses: [
      "Picos sazonais podem tornar disponibilidade e proteção de aplicações temas relevantes.",
    ],
    sources: [makeSource("horizonte-portal", "Portal acadêmico fictício")],
    titles: [
      "Gerente de Segurança da Informação",
      "Cloud Security",
      "Diretor de TI",
    ],
    navigatorQuery:
      '("Gerente de Segurança da Informação" OR "Cloud Security" OR "Diretor de TI")',
    status: "Aprovada para pesquisar leads",
    tags: ["demo", "portal"],
    discoveredAt: "2026-08-12",
    reviewedAt: "2026-08-13",
    demo: true,
    possibleDuplicate: false,
  },
  {
    id: "demo-verde",
    name: "Fundação Verde Amanhã (Demonstração)",
    domain: "verde-amanha-demo.example",
    vertical: "Non-Profit",
    subsegment: "Organizações sem fins lucrativos",
    city: "Recife",
    state: "PE",
    country: "Brasil",
    size: "Pequeno",
    employees: "50–100",
    description: "Organização fictícia com baixa aderência atual.",
    solution: "WAAP",
    score: 44,
    apiScore: 32,
    waapScore: 51,
    guardicoreScore: 29,
    breakdown: {
      verticalFit: 12,
      sizeComplexity: 5,
      digitalPresence: 10,
      transactionalChannels: 5,
      recentSignals: 5,
      solutionFit: 5,
      evidenceQuality: 2,
    },
    recommendation:
      "Manter fora da prioridade atual salvo novo sinal relevante.",
    confirmedFacts: ["Mantém site institucional fictício."],
    commercialSignals: [],
    hypotheses: ["Sem sinais suficientes para uma hipótese comercial forte."],
    sources: [makeSource("verde-site", "Site institucional fictício")],
    titles: ["Diretor de TI"],
    navigatorQuery: '("Diretor de TI" OR "Segurança da Informação")',
    status: "Sem aderência",
    tags: ["demo"],
    discoveredAt: "2026-08-11",
    reviewedAt: "2026-08-12",
    demo: true,
    possibleDuplicate: false,
  },
];

export { verticalNames };
